In [12]:
import pandas as pd
import numpy as py

income_data1 = pd.read_csv("income1.csv")

income_data1.head()

,Id,Id2,Geography,Estimate; Per capita income in the past 12 months (in 2017 inflation-adjusted dollars),Margin of Error; Per capita income in the past 12 months (in 2017 inflation-adjusted dollars)
0,8600000US20001,20001,ZCTA5 20001,54353,2353
1,8600000US20002,20002,ZCTA5 20002,49452,1563
2,8600000US20003,20003,ZCTA5 20003,63600,2632
3,8600000US20004,20004,ZCTA5 20004,117432,12612
4,8600000US20005,20005,ZCTA5 20005,76658,5296

In [22]:
income_data2 = pd.read_csv("income2.csv")
income_data2.head()

,Id,Id2,Geography,Estimate; EMPLOYMENT STATUS - Population 16 years and over,Margin of Error; EMPLOYMENT STATUS - Population 16 years and over,Percent; EMPLOYMENT STATUS - Population 16 years and over,Percent Margin of Error; EMPLOYMENT STATUS - Population 16 years and over,Estimate; EMPLOYMENT STATUS - Population 16 years and over - In labor force,Margin of Error; EMPLOYMENT STATUS - Population 16 years and over - In labor force,Percent; EMPLOYMENT STATUS - Population 16 years and over - In labor force,...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - All people - 18 years and over - 65 years and over,Percent Margin of Error; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - All people - 18 years and over - 65 years and over,Estimate; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - People in families,Margin of Error; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - People in families,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - People in families,Percent Margin of Error; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - People in families,Estimate; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - Unrelated individuals 15 years and over,Margin of Error; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - Unrelated individuals 15 years and over,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - Unrelated individuals 15 years and over,Percent Margin of Error; PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL - Unrelated individuals 15 years and over
0,8600000US20001,20001,ZCTA5 20001,41692,1106,41692,(X),30607,875,73.4,...,26.5,4.2,(X),(X),15.2,3.6,(X),(X),16.9,2.3
1,8600000US20002,20002,ZCTA5 20002,52867,1323,52867,(X),38531,1069,72.9,...,14.8,2.6,(X),(X),12.7,2.5,(X),(X),19.7,1.8
2,8600000US20003,20003,ZCTA5 20003,26330,806,26330,(X),18819,666,71.5,...,13.8,4.1,(X),(X),10.1,3.5,(X),(X),14,2.3
3,8600000US20004,20004,ZCTA5 20004,1610,189,1610,(X),1416,181,88,...,0,15.7,(X),(X),0,5.1,(X),(X),9.4,3.8
4,8600000US20005,20005,ZCTA5 20005,12311,757,12311,(X),10336,705,84,...,34.4,11.3,(X),(X),5,3.8,(X),(X),14.3,2.9

In [24]:
income_data2 = income_data2.iloc[:,[0,3]]
income_data2

,Id,Percent; EMPLOYMENT STATUS - Population 16 years and over
0,8600000US20001,41692
1,8600000US20002,52867
2,8600000US20003,26330
3,8600000US20004,1610
4,8600000US20005,12311
5,8600000US20006,2780
6,8600000US20007,23866
7,8600000US20008,26034
8,8600000US20009,46797
9,8600000US20010,28736
10,8600000US20011,54799
11,8600000US20012,12565
12,8600000US20015,12349
13,8600000US20016,29230
14,8600000US20017,16815
15,8600000US20018,16617
16,8600000US20019,47261
17,8600000US20020,41842
18,8600000US20024,11342
19,8600000US20032,30806
20,8600000US20036,5653
21,8600000US20037,14362
22,8600000US20045,0
23,8600000US20052,686
24,8600000US20053,0
25,8600000US20057,3709
26,8600000US20064,2213
27,8600000US20105,12329
28,8600000US20106,4409
29,8600000US20109,30363
...,...,...
1399,8600000US24612,218
1400,8600000US24613,333
1401,8600000US24614,6150
1402,8600000US24620,2359
1403,8600000US24622,736
1404,8600000US24628,296
1405,8600000US24630,6138
1406,8600000US24631,2242
1407,8600000US24634,460
1408,8600000US24635,1374
1409,8600000US24637,3108
1410,8600000US24639,2403
1411,8600000US24641,4620
1412,8600000US24646,623
1413,8600000US24649,2482
1414,8600000US24651,4748
1415,8600000US24656,2590
1416,8600000US24657,346
1417,8600000US27024,2447
1418,8600000US27030,29792
1419,8600000US27048,7090
1420,8600000US27288,18711
1421,8600000US27551,1520
1422,8600000US27553,2114
1423,8600000US27818,1124
1424,8600000US27850,5976
1425,8600000US27853,227
1426,8600000US28623,1353
1427,8600000US28631,688
1428,8600000US28643,3037

In [36]:
income_data3 = pd.read_csv("income3.csv")
income_data3.head()
list(income_data3)

['Id',
 'Id2',
 'Geography',
 'Number; Estimate; Households',
 'Number; Margin of Error; Households',
 'Percent Distribution; Estimate; Households',
 'Percent Distribution; Margin of Error; Households',
 'Median income (dollars); Estimate; Households',
 'Median income (dollars); Margin of Error; Households',
 'Number; Estimate; Households - One race-- - White',
 'Number; Margin of Error; Households - One race-- - White',
 'Percent Distribution; Estimate; Households - One race-- - White',
 'Percent Distribution; Margin of Error; Households - One race-- - White',
 'Median income (dollars); Estimate; Households - One race-- - White',
 'Median income (dollars); Margin of Error; Households - One race-- - White',
 'Number; Estimate; Households - One race-- - Black or African American',
 'Number; Margin of Error; Households - One race-- - Black or African American',
 'Percent Distribution; Estimate; Households - One race-- - Black or African American',
 'Percent Distribution; Margin of Error; Households - One race-- - Black or African American',
 'Median income (dollars); Estimate; Households - One race-- - Black or African American',
 'Median income (dollars); Margin of Error; Households - One race-- - Black or African American',
 'Number; Estimate; Households - One race-- - American Indian and Alaska Native',
 'Number; Margin of Error; Households - One race-- - American Indian and Alaska Native',
 'Percent Distribution; Estimate; Households - One race-- - American Indian and Alaska Native',
 'Percent Distribution; Margin of Error; Households - One race-- - American Indian and Alaska Native',
 'Median income (dollars); Estimate; Households - One race-- - American Indian and Alaska Native',
 'Median income (dollars); Margin of Error; Households - One race-- - American Indian and Alaska Native',
 'Number; Estimate; Households - One race-- - Asian',
 'Number; Margin of Error; Households - One race-- - Asian',
 'Percent Distribution; Estimate; Households - One race-- - Asian',
 'Percent Distribution; Margin of Error; Households - One race-- - Asian',
 'Median income (dollars); Estimate; Households - One race-- - Asian',
 'Median income (dollars); Margin of Error; Households - One race-- - Asian',
 'Number; Estimate; Households - One race-- - Native Hawaiian and Other Pacific Islander',
 'Number; Margin of Error; Households - One race-- - Native Hawaiian and Other Pacific Islander',
 'Percent Distribution; Estimate; Households - One race-- - Native Hawaiian and Other Pacific Islander',
 'Percent Distribution; Margin of Error; Households - One race-- - Native Hawaiian and Other Pacific Islander',
 'Median income (dollars); Estimate; Households - One race-- - Native Hawaiian and Other Pacific Islander',
 'Median income (dollars); Margin of Error; Households - One race-- - Native Hawaiian and Other Pacific Islander',
 'Number; Estimate; Households - One race-- - Some other race',
 'Number; Margin of Error; Households - One race-- - Some other race',
 'Percent Distribution; Estimate; Households - One race-- - Some other race',
 'Percent Distribution; Margin of Error; Households - One race-- - Some other race',
 'Median income (dollars); Estimate; Households - One race-- - Some other race',
 'Median income (dollars); Margin of Error; Households - One race-- - Some other race',
 'Number; Estimate; Households - Two or more races',
 'Number; Margin of Error; Households - Two or more races',
 'Percent Distribution; Estimate; Households - Two or more races',
 'Percent Distribution; Margin of Error; Households - Two or more races',
 'Median income (dollars); Estimate; Households - Two or more races',
 'Median income (dollars); Margin of Error; Households - Two or more races',
 'Number; Estimate; Hispanic or Latino origin (of any race)',
 'Number; Margin of Error; Hispanic or Latino origin (of any race)',
 'Percent Distribution; Estimate; Hispanic or Latino origin (of any race)',
 'Percent Distribution; Margin of Error; Hispanic or Latino origin (of any race)',
 'Median income (dollars); Estimate; Hispanic or Latino origin (of any race)',
 'Median income (dollars); Margin of Error; Hispanic or Latino origin (of any race)',
 'Number; Estimate; White alone, not Hispanic or Latino',
 'Number; Margin of Error; White alone, not Hispanic or Latino',
 'Percent Distribution; Estimate; White alone, not Hispanic or Latino',
 'Percent Distribution; Margin of Error; White alone, not Hispanic or Latino',
 'Median income (dollars); Estimate; White alone, not Hispanic or Latino',
 'Median income (dollars); Margin of Error; White alone, not Hispanic or Latino',
 'Number; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 15 to 24 years',
 'Number; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 15 to 24 years',
 'Percent Distribution; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 15 to 24 years',
 'Percent Distribution; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 15 to 24 years',
 'Median income (dollars); Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 15 to 24 years',
 'Median income (dollars); Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 15 to 24 years',
 'Number; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 25 to 44 years',
 'Number; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 25 to 44 years',
 'Percent Distribution; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 25 to 44 years',
 'Percent Distribution; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 25 to 44 years',
 'Median income (dollars); Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 25 to 44 years',
 'Median income (dollars); Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 25 to 44 years',
 'Number; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 45 to 64 years',
 'Number; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 45 to 64 years',
 'Percent Distribution; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 45 to 64 years',
 'Percent Distribution; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 45 to 64 years',
 'Median income (dollars); Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 45 to 64 years',
 'Median income (dollars); Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 45 to 64 years',
 'Number; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 65 years and over',
 'Number; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 65 years and over',
 'Percent Distribution; Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 65 years and over',
 'Percent Distribution; Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 65 years and over',
 'Median income (dollars); Estimate; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 65 years and over',
 'Median income (dollars); Margin of Error; HOUSEHOLD INCOME BY AGE OF HOUSEHOLDER - 65 years and over',
 'Number; Estimate; FAMILIES - Families',
 'Number; Margin of Error; FAMILIES - Families',
 'Percent Distribution; Estimate; FAMILIES - Families',
 'Percent Distribution; Margin of Error; FAMILIES - Families',
 'Median income (dollars); Estimate; FAMILIES - Families',
 'Median income (dollars); Margin of Error; FAMILIES - Families',
 'Number; Estimate; FAMILIES - Families - With own children of householder under 18 years',
 'Number; Margin of Error; FAMILIES - Families - With own children of householder under 18 years',
 'Percent Distribution; Estimate; FAMILIES - Families - With own children of householder under 18 years',
 'Percent Distribution; Margin of Error; FAMILIES - Families - With own children of householder under 18 years',
 'Median income (dollars); Estimate; FAMILIES - Families - With own children of householder under 18 years',
 'Median income (dollars); Margin of Error; FAMILIES - Families - With own children of householder under 18 years',
 'Number; Estimate; FAMILIES - Families - With no own children of householder under 18 years',
 'Number; Margin of Error; FAMILIES - Families - With no own children of householder under 18 years',
 'Percent Distribution; Estimate; FAMILIES - Families - With no own children of householder under 18 years',
 'Percent Distribution; Margin of Error; FAMILIES - Families - With no own children of householder under 18 years',
 'Median income (dollars); Estimate; FAMILIES - Families - With no own children of householder under 18 years',
 'Median income (dollars); Margin of Error; FAMILIES - Families - With no own children of householder under 18 years',
 'Number; Estimate; FAMILIES - Families - Married-couple families',
 'Number; Margin of Error; FAMILIES - Families - Married-couple families',
 'Percent Distribution; Estimate; FAMILIES - Families - Married-couple families',
 'Percent Distribution; Margin of Error; FAMILIES - Families - Married-couple families',
 'Median income (dollars); Estimate; FAMILIES - Families - Married-couple families',
 'Median income (dollars); Margin of Error; FAMILIES - Families - Married-couple families',
 'Number; Estimate; FAMILIES - Families - Married-couple families - With own children under 18 years',
 'Number; Margin of Error; FAMILIES - Families - Married-couple families - With own children under 18 years',
 'Percent Distribution; Estimate; FAMILIES - Families - Married-couple families - With own children under 18 years',
 'Percent Distribution; Margin of Error; FAMILIES - Families - Married-couple families - With own children under 18 years',
 'Median income (dollars); Estimate; FAMILIES - Families - Married-couple families - With own children under 18 years',
 'Median income (dollars); Margin of Error; FAMILIES - Families - Married-couple families - With own children under 18 years',
 'Number; Estimate; FAMILIES - Families - Female householder, no husband present',
 'Number; Margin of Error; FAMILIES - Families - Female householder, no husband present',
 'Percent Distribution; Estimate; FAMILIES - Families - Female householder, no husband present',
 'Percent Distribution; Margin of Error; FAMILIES - Families - Female householder, no husband present',
 'Median income (dollars); Estimate; FAMILIES - Families - Female householder, no husband present',
 'Median income (dollars); Margin of Error; FAMILIES - Families - Female householder, no husband present',
 'Number; Estimate; FAMILIES - Families - Female householder, no husband present - With own children under 18 years',
 'Number; Margin of Error; FAMILIES - Families - Female householder, no husband present - With own children under 18 years',
 'Percent Distribution; Estimate; FAMILIES - Families - Female householder, no husband present - With own children under 18 years',
 'Percent Distribution; Margin of Error; FAMILIES - Families - Female householder, no husband present - With own children under 18 years',
 'Median income (dollars); Estimate; FAMILIES - Families - Female householder, no husband present - With own children under 18 years',
 'Median income (dollars); Margin of Error; FAMILIES - Families - Female householder, no husband present - With own children under 18 years',
 'Number; Estimate; FAMILIES - Families - Male householder, no wife present',
 'Number; Margin of Error; FAMILIES - Families - Male householder, no wife present',
 'Percent Distribution; Estimate; FAMILIES - Families - Male householder, no wife present',
 'Percent Distribution; Margin of Error; FAMILIES - Families - Male householder, no wife present',
 'Median income (dollars); Estimate; FAMILIES - Families - Male householder, no wife present',
 'Median income (dollars); Margin of Error; FAMILIES - Families - Male householder, no wife present',
 'Number; Estimate; FAMILIES - Families - Male householder, no wife present - With own children under 18 years',
 'Number; Margin of Error; FAMILIES - Families - Male householder, no wife present - With own children under 18 years',
 'Percent Distribution; Estimate; FAMILIES - Families - Male householder, no wife present - With own children under 18 years',
 'Percent Distribution; Margin of Error; FAMILIES - Families - Male householder, no wife present - With own children under 18 years',
 'Median income (dollars); Estimate; FAMILIES - Families - Male householder, no wife present - With own children under 18 years',
 'Median income (dollars); Margin of Error; FAMILIES - Families - Male householder, no wife present - With own children under 18 years',
 'Number; Estimate; FAMILY INCOME BY FAMILY SIZE - 2-person families',
 'Number; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 2-person families',
 'Percent Distribution; Estimate; FAMILY INCOME BY FAMILY SIZE - 2-person families',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 2-person families',
 'Median income (dollars); Estimate; FAMILY INCOME BY FAMILY SIZE - 2-person families',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY FAMILY SIZE - 2-person families',
 'Number; Estimate; FAMILY INCOME BY FAMILY SIZE - 3-person families',
 'Number; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 3-person families',
 'Percent Distribution; Estimate; FAMILY INCOME BY FAMILY SIZE - 3-person families',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 3-person families',
 'Median income (dollars); Estimate; FAMILY INCOME BY FAMILY SIZE - 3-person families',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY FAMILY SIZE - 3-person families',
 'Number; Estimate; FAMILY INCOME BY FAMILY SIZE - 4-person families',
 'Number; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 4-person families',
 'Percent Distribution; Estimate; FAMILY INCOME BY FAMILY SIZE - 4-person families',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 4-person families',
 'Median income (dollars); Estimate; FAMILY INCOME BY FAMILY SIZE - 4-person families',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY FAMILY SIZE - 4-person families',
 'Number; Estimate; FAMILY INCOME BY FAMILY SIZE - 5-person families',
 'Number; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 5-person families',
 'Percent Distribution; Estimate; FAMILY INCOME BY FAMILY SIZE - 5-person families',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 5-person families',
 'Median income (dollars); Estimate; FAMILY INCOME BY FAMILY SIZE - 5-person families',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY FAMILY SIZE - 5-person families',
 'Number; Estimate; FAMILY INCOME BY FAMILY SIZE - 6-person families',
 'Number; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 6-person families',
 'Percent Distribution; Estimate; FAMILY INCOME BY FAMILY SIZE - 6-person families',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 6-person families',
 'Median income (dollars); Estimate; FAMILY INCOME BY FAMILY SIZE - 6-person families',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY FAMILY SIZE - 6-person families',
 'Number; Estimate; FAMILY INCOME BY FAMILY SIZE - 7-or-more person families',
 'Number; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 7-or-more person families',
 'Percent Distribution; Estimate; FAMILY INCOME BY FAMILY SIZE - 7-or-more person families',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY FAMILY SIZE - 7-or-more person families',
 'Median income (dollars); Estimate; FAMILY INCOME BY FAMILY SIZE - 7-or-more person families',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY FAMILY SIZE - 7-or-more person families',
 'Number; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - No earners',
 'Number; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - No earners',
 'Percent Distribution; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - No earners',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - No earners',
 'Median income (dollars); Estimate; FAMILY INCOME BY NUMBER OF EARNERS - No earners',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - No earners',
 'Number; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 1 earner',
 'Number; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 1 earner',
 'Percent Distribution; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 1 earner',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 1 earner',
 'Median income (dollars); Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 1 earner',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 1 earner',
 'Number; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 2 earners',
 'Number; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 2 earners',
 'Percent Distribution; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 2 earners',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 2 earners',
 'Median income (dollars); Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 2 earners',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 2 earners',
 'Number; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 3 or more earners',
 'Number; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 3 or more earners',
 'Percent Distribution; Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 3 or more earners',
 'Percent Distribution; Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 3 or more earners',
 'Median income (dollars); Estimate; FAMILY INCOME BY NUMBER OF EARNERS - 3 or more earners',
 'Median income (dollars); Margin of Error; FAMILY INCOME BY NUMBER OF EARNERS - 3 or more earners',
 'Number; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households',
 'Number; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households',
 'Percent Distribution; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households',
 'Percent Distribution; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households',
 'Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households',
 'Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households',
 'Number; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder',
 'Number; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder',
 'Percent Distribution; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder',
 'Percent Distribution; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder',
 'Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder',
 'Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder',
 'Number; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Living alone',
 'Number; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Living alone',
 'Percent Distribution; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Living alone',
 'Percent Distribution; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Living alone',
 'Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Living alone',
 'Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Living alone',
 'Number; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Not living alone',
 'Number; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Not living alone',
 'Percent Distribution; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Not living alone',
 'Percent Distribution; Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Not living alone',
 'Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Not living alone',
 'Median income (dollars); Margin of Error; NONFAMILY HOUSEHOLDS - Nonfamily households - Female householder - Not living alone',

In [38]:
income_data32 = income_data3.loc[:,["Id2",'Number; Estimate; Households','Median income (dollars); Estimate; Households','Number; Estimate; FAMILIES - Families','Median income (dollars); Estimate; FAMILIES - Families','Number; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households','Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households',]]
income_data32

,Id2,Number; Estimate; Households,Median income (dollars); Estimate; Households,Number; Estimate; FAMILIES - Families,Median income (dollars); Estimate; FAMILIES - Families,Number; Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households,Median income (dollars); Estimate; NONFAMILY HOUSEHOLDS - Nonfamily households
0,20001,18764,100447,6040,113317,12724,93786
1,20002,26217,82022,10665,101998,15552,69683
2,20003,12394,118607,5296,167746,7098,94339
3,20004,1163,144583,280,248672,883,135189
4,20005,8172,94506,1668,142821,6504,83333
5,20006,616,40000,13,-,603,37212
6,20007,11885,123154,4628,220000,7257,83760
7,20008,15611,120342,5668,205551,9943,94350
8,20009,27184,102941,7316,143796,19868,94213
9,20010,12593,81106,5565,88278,7028,77681
10,20011,24288,65327,13424,85369,10864,45058
11,20012,5945,87824,3414,121154,2531,56550
12,20015,6437,158401,3872,242679,2565,74782
13,20016,13757,140545,7119,219013,6638,82706
14,20017,7637,76502,3935,100170,3702,56101
15,20018,7890,63764,3877,87768,4013,32313
16,20019,23499,35487,13158,43597,10341,25550
17,20020,21135,34508,11873,36564,9262,29597
18,20024,7309,75696,2331,117527,4978,64597
19,20032,14627,35047,8849,41351,5778,27632
20,20036,4171,80977,848,157479,3323,68211
21,20037,6381,80133,1572,137833,4809,67848
22,20045,0,-,0,-,0,-
23,20052,0,-,0,-,0,-
24,20053,0,-,0,-,0,-
25,20057,0,-,0,-,0,-
26,20064,0,-,0,-,0,-
27,20105,5675,143204,4644,154043,1031,88397
28,20106,2147,80117,1583,97917,564,56667
29,20109,13089,67891,8824,66203,4265,57123
...,...,...,...,...,...,...,...
1399,24612,112,21250,58,24500,54,14479
1400,24613,231,-,88,67639,143,-
1401,24614,2907,34347,1917,46133,990,16957
1402,24620,1126,21684,844,24696,282,12667
1403,24622,425,27539,255,36563,170,14052
1404,24628,123,-,102,-,21,-
1405,24630,2846,42963,2115,52144,731,19392
1406,24631,853,32324,576,40481,277,17969
1407,24634,223,36696,160,49375,63,19009
1408,24635,253,23750,123,38750,130,17647
1409,24637,1589,52070,1211,66354,378,32500
1410,24639,1224,30328,716,51053,508,20114
1411,24641,2470,29076,1389,48277,1081,18030
1412,24646,287,31083,222,44063,65,20125
1413,24649,1133,40300,732,48500,401,15491
1414,24651,2218,45896,1575,62560,643,19650
1415,24656,1261,34093,813,47930,448,25435
1416,24657,167,38125,132,40648,35,11902
1417,27024,1079,34939,889,38365,190,28269
1418,27030,15151,36551,9915,48823,5236,18594
1419,27048,3306,50230,2463,60132,843,24271
1420,27288,9538,36740,6010,44593,3528,22143
1421,27551,784,41371,513,56250,271,25699
1422,27553,835,36051,490,60268,345,18295
1423,27818,530,34028,387,41435,143,10462
1424,27850,3190,40401,2038,51653,1152,20694
1425,27853,133,46010,73,67014,60,-
1426,28623,717,41607,510,46227,207,19219
1427,28631,330,41250,304,39107,26,-
1428,28643,1583,38638,1141,44727,442,13387